// styles.js
export const styles = {
    body: {
      margin: 0,
      padding: 0,
      boxSizing: "border-box",
      fontFamily: "Arial, Helvetica, sans-serif",
      backgroundColor: "#ffd8be",
    },
    header: {
      background: "#1a2338",
      color: "white",
      display: "flex",
      flexWrap: "wrap",
      justifyContent: "center",
      alignItems: "center",
      gap: "10px",
    },
    logo: {
      marginRight: "auto",
      marginLeft: "10px",
      cursor: "pointer",
      transition: "all 0.5s ease-in-out 0s",
    },
    btnCta: {
      marginRight: "10px",
      border: "none",
      fontSize: "20px",
      padding: "6px 12px",
      background: "darkorange",
      color: "#eaeaea",
      borderRadius: "8px",
      cursor: "pointer",
      gap: "5px",
    },
    navUl: {
      display: "flex",
      padding: "20px",
    },
    li: {
      listStyleType: "none",
      padding: "10px",
    },
    liA: {
      transition: "all 0.5s ease-in-out 0s",
      color: "white",
      textDecoration: "none",
    },
    liAHover: {
      color: "aquamarine", // bisa dipakai di onMouseEnter / onMouseLeave
    },
    container: {
      maxWidth: "1200px",
      margin: "0 auto",
      padding: "20px 0",
      height: "90vh",
    },
    intro: {
      display: "flex",
      flexDirection: "column",
      justifyContent: "center",
      alignItems: "center",
      gap: "20px",
      textAlign: "center",
    },
    title: {
      fontSize: "24px",
      fontWeight: "bold",
    },
    description: {
      fontSize: "20px",
      fontWeight: "bolder",
    },
    imgVideo: {
      width: "100%",
      height: "auto",
      padding: "10px",
      borderRadius: "8px",
    },
    parallax: {
      backgroundImage: "url('/home/asset/download__2_-removebg-preview.png')",
      backgroundAttachment: "fixed",
      backgroundPosition: "center",
      backgroundRepeat: "no-repeat",
      backgroundSize: "cover",
      height: "155vh",
    },
    about: {
      display: "flex",
      justifyContent: "center",
      alignItems: "center",
      flexDirection: "column",
      background: "#1a2338",
      color: "#eaeaea",
      padding: "40px",
      gap: "10px",
    },
    btn: {
      marginTop: "10px",
    },
    containers: {
      backgroundImage: "url('/home/asset/wow.png')",
      backgroundAttachment: "fixed",
      backgroundPosition: "center",
      backgroundRepeat: "no-repeat",
      backgroundSize: "cover",
      height: "100vh",
    },
    cardContainer: {
      display: "flex",
      flexDirection: "row",
      justifyContent: "center",
      alignItems: "center",
      background: "#fff5ba",
      backdropFilter: "blur(10px)",
      WebkitBackdropFilter: "blur(10px)",
      color: "black",
      padding: "20px",
      borderRadius: "12px",
      boxShadow: "0 4px 20px rgba(0,0,0,0.3)",
      width: "300px",
      marginTop: "20px",
    },
    cardItem: {
      display: "flex",
      justifyContent: "center",
      gap: "20px",
      marginTop: "10px",
    },
  };
  